services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../../src:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
    networks:
      - laravel
    depends_on:
      - app
  app:
    build:
      context: ./php
    image: michelbolzon/tibia-scrapper-app:latest
    volumes:
      - ./../../src:/var/www/html
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - XDEBUG_MODE=off
    networks:
      - laravel
networks:
  laravel:
    driver: bridge