services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - laravel
volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
