name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: cp src/.env.testing infra/app_web/.env

      - name: Build and start containers
        run: docker compose -f infra/app_web/docker-compose.yml up -d

      - name: Install Dependencies
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app chmod -R 777 storage bootstrap/cache

      - name: Create SqlLite database
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app touch database/database.sqlite

      - name: Generate App key
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan key:generate

      - name: Run Migrations
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan migrate --force

      - name: Run Seeders
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan db:seed

      - name: Run Npm Install
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app npm ci

      - name: Run Npm Build
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app npm run build

      - name: Run Tests with PHPUnit + Xdebug
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app vendor/bin/phpunit --colors=never

  deploy:
    name: Deploy to Servers
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Front
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST_FRONT }}
          username: ${{ secrets.DEPLOY_USER_FRONT }}
          key: ${{ secrets.DEPLOY_SSH_KEY_FRONT }}
          script: |
            cd /var/www/tibia-hunteds-site
            git fetch origin main
            git reset --hard origin/main
            docker exec app_web-app-1 composer install --no-dev --optimize-autoloader --no-interaction --no-ansi
            docker exec app_web-app-1 php artisan config:cache
            docker exec app_web-app-1 php artisan route:cache
            docker exec app_web-app-1 php artisan view:cache

      - name: Deploy to Crawler
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST_CRAWLER }}
          username: ${{ secrets.DEPLOY_USER_CRAWLER }}
          key: ${{ secrets.DEPLOY_SSH_KEY_CRAWLER }}
          script: |
            cd /var/www/tibia-hunteds-site
            git fetch origin main
            git reset --hard origin/main
            cd /var/www/tibia-hunteds-site/src
            composer install --no-dev --optimize-autoloader --no-interaction --no-ansi
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart world-scraper.service
            sudo systemctl restart schedule-run.service
