name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: cp src/.env.testing infra/app_web/.env

      # Sobe os containers com o app e nginx
      - name: Build and start containers
        run: docker compose -f infra/app_web/docker-compose.yml up -d

      # Instala dependências via composer dentro do container
      - name: Install Dependencies
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app chmod -R 777 storage bootstrap/cache

      - name: Create SqlLite database
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app touch database/database.sqlite

      - name: Generate App key
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan key:generate

      - name: Run Migrations
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan migrate --force

      - name: Run Seeders
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app php artisan db:seed

      - name: Run Npm Install
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app npm ci

      - name: Run Npm Build
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app npm run build

      - name: Run Tests with PHPUnit + Xdebug
        run: docker compose -f infra/app_web/docker-compose.yml exec -T app vendor/bin/phpunit --colors=never